<?php define("SiteTitle","NEWS ONLINE");
define("BaiXN","POPULAR NEWS");
define("DangNhap","LOGIN");
define("UserName","Username");
define("Password","Password");
define("Remember","Remember");
define("Register","Register");
define("ForgotPassword","Forgot password");
define("ChangePassword","Change password");
define("Logout","Logout");
define("MenuHome","Home");
