<?php define("SiteTitle","TIN TỨC TRỰC TUYẾN");
define("BaiXN","BÀI XEM NHIỀU");
define("DangNhap","Đăng nhập");
define("UserName","Tên đăng nhập");
define("Password","Mật khẩu");
define("Remember","Ghi nhớ");
define("Register","Đăng ký");
define("ForgotPassword","Quên mật khẩu");
define("ChangePassword","Đổi mật khẩu");
define("Logout","Thoát");
define("MenuHome","Trang Chu");
